### ISSUE TITLE
Unable to open project with Xcode 15.4

### ISSUE THREAD

**Issue by laventura** [huggingface/sam2-studio#20]
I get this error when trying to open with a recently updated Xcode 15.4 (on MacOS Sonoma 14.5)

```
The project at ‘/Users/atul/Projects/dev-workspace/sam2-studio/SAM2-Demo.xcodeproj’ cannot be opened because it is in a future Xcode project file format. Adjust the project format using a compatible version of Xcode to allow it to be opened by this version of Xcode.
```

What version of Xcode is used for this?

Thanks
<img width="252" alt="image" src="https://github.com/user-attachments/assets/38418432-01f3-43cd-92d4-3a70e7d99f64">

**Comment by btoms20** [comment]
Xcode 16 RC can open it

**Comment by FL33TW00D** [comment]
Should be fixed!

**Comment by pcuenca** [comment]
Fixed by @FL33TW00D in https://github.com/huggingface/sam2-studio/commit/52e7a5f990fffbbd5a0350e3b6be3a7fbb0fbb32 🙌

**Comment by FL33TW00D** [comment]
Please reopen the issue if it persists.
