### ISSUE TITLE
Unable to download the SAM 2.1 model. (The link is broken)

### ISSUE THREAD

**Issue by happyjem** [huggingface/sam2-studio#30]
The source code contains the 2.1 Tiny model, but the links for the other models are not valid.

**Comment by pcuenca** [comment]
Hi @happyjem, thanks for reporting! These links all work for me:

- [SAM 2.1 Tiny](https://huggingface.co/apple/coreml-sam2.1-tiny)
- [SAM 2.1 Small](https://huggingface.co/apple/coreml-sam2.1-small)
- [SAM 2.1 Base](https://huggingface.co/apple/coreml-sam2.1-baseplus)
- [SAM 2.1 Large](https://huggingface.co/apple/coreml-sam2.1-large)

Are they not working for you?

**Comment by pcuenca** [comment]
My apologies, the models had not been made public to everyone 🤦 They should all work now!
