### ISSUE TITLE
How Use Large SAM2 with the compiler

### ISSUE THREAD

**Issue by Sane-viola** [huggingface/sam2-studio#34]
Hello, 
Little problem for me.
I install the package on Apple huggingface : SAM2_1LargeImageEncoderFLOAT16 etc...
But in the swift code, this doesn't compile and run due to the presence of the small in the code. How debug this ? 
Thanks a lot :)

**Comment by Sane-viola** [comment]
I found the solution : 
Remplace each error with : 2_1Large instead of 2Small.
Sorry for the inconvenience

**Comment by pcuenca** [comment]
Exactly, you need to update the source code as well! We are planning to add a way to select the model at runtime so these changes are not necessary, but can't provide an estimate about the time when this will be done.

Thanks a lot for reaching out, closing the issue now!
